# Generated by Django 5.2 on 2025-04-21 02:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(db_column='ID_CATEGORIA', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='NOMBRE', max_length=50)),
            ],
            options={
                'db_table': 'CATEGORIA',
            },
        ),
        migrations.CreateModel(
            name='Plataforma',
            fields=[
                ('id_categoria', models.AutoField(db_column='ID_PLATAFORMA', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='NOMBRE', max_length=50)),
            ],
            options={
                'db_table': 'PLATAFORMA',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.AutoField(db_column='ID_ROL', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='NOMBRE', max_length=50)),
            ],
            options={
                'db_table': 'MAIN_ROL',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id_usuario', models.AutoField(db_column='ID_USUARIO', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='NOMBRE', max_length=100, null=True)),
                ('apellido', models.CharField(db_column='APELLIDO', max_length=100, null=True)),
                ('correo', models.EmailField(db_column='CORREO', max_length=254, unique=True)),
                ('direccion', models.CharField(blank=True, db_column='DIRECCION', max_length=255, null=True)),
                ('telefono', models.CharField(blank=True, db_column='TELEFONO', max_length=20, null=True)),
                ('clave', models.CharField(db_column='CLAVE', max_length=255)),
                ('is_active', models.BooleanField(db_column='ACTIVO', default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('rol', models.ForeignKey(db_column='ID_ROL', on_delete=django.db.models.deletion.PROTECT, to='miapp.rol')),
            ],
            options={
                'db_table': 'USUARIO',
            },
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id_compra', models.AutoField(db_column='ID_COMPRA', primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True, db_column='FECHA')),
                ('total', models.DecimalField(db_column='TOTAL', decimal_places=2, max_digits=10)),
                ('estado', models.CharField(db_column='ESTADO', max_length=50)),
                ('usuario', models.ForeignKey(db_column='ID_USUARIO', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'COMPRA',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(db_column='ID_PRODUCTO', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='NOMBRE', max_length=100)),
                ('descripcion', models.TextField(blank=True, db_column='DESCRIPCION', null=True)),
                ('precio', models.DecimalField(db_column='PRECIO', decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField(db_column='STOCK', default=0)),
                ('imagen_url', models.CharField(blank=True, db_column='IMAGEN_URL', max_length=255, null=True)),
                ('categoria', models.ForeignKey(db_column='ID_CATEGORIA', on_delete=django.db.models.deletion.CASCADE, to='miapp.categoria')),
                ('plataforma', models.ForeignKey(db_column='ID_PLATAFORMA', on_delete=django.db.models.deletion.CASCADE, to='miapp.plataforma')),
            ],
            options={
                'db_table': 'PRODUCTO',
            },
        ),
        migrations.CreateModel(
            name='DetalleCompra',
            fields=[
                ('id_detalle', models.AutoField(db_column='ID_DETALLE', primary_key=True, serialize=False)),
                ('cantidad', models.PositiveIntegerField(db_column='CANTIDAD')),
                ('precio_unitario', models.DecimalField(db_column='PRECIO_UNITARIO', decimal_places=2, max_digits=10)),
                ('compra', models.ForeignKey(db_column='ID_COMPRA', on_delete=django.db.models.deletion.CASCADE, to='miapp.compra')),
                ('producto', models.ForeignKey(db_column='ID_PRODUCTO', on_delete=django.db.models.deletion.CASCADE, to='miapp.producto')),
            ],
            options={
                'db_table': 'DETALLE_COMPRA',
            },
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id_carrito', models.AutoField(db_column='ID_CARRITO', primary_key=True, serialize=False)),
                ('cantidad', models.PositiveIntegerField(db_column='CANTIDAD')),
                ('usuario', models.ForeignKey(db_column='ID_USUARIO', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('producto', models.ForeignKey(db_column='ID_PRODUCTO', on_delete=django.db.models.deletion.CASCADE, to='miapp.producto')),
            ],
            options={
                'db_table': 'CARRITO',
            },
        ),
    ]
